### ISSUE TITLE
Upload package to conda

### ISSUE THREAD

**Issue by danieljfarrell** [bcb/jsonrpcclient#130]
I have made a [conda-build](https://docs.conda.io/projects/conda-build/en/latest/) script which can be used to upload jsonrpcclient to Anaconda Cloud so it can be installed with the Conda package manager.

`conda install -c danieljfarrell_teraview jsonrpcclient`

The script is below. Please let me know if I can assist you in upload the package to the official channel.

```yaml
{% set name = "jsonrpcclient"%}
{% set version = "3.3.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/bcb/jsonrpcclient/archive/3.3.3.tar.gz
  sha256: 2ebe45957f3cc55c35d1e983e5f8685e4669218f7be05946ef3f4efad4739efc

build:
  number: 0
  script: "python -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
  run:
    - python

about:
  home: https://github.com/bcb/jsonrpcclient
  license: MIT License
  license_family: MIT
  license_file: 
  summary: Send JSON-RPC requests in Python
  doc_url: https://jsonrpcclient.readthedocs.io/
  dev_url: 

extra:
  recipe-maintainers:
    - bcb
```
